#pragma once

#include QMK_KEYBOARD_H
 
// useful macros
#define __EMPTY_2__ KC_TRNS, KC_TRNS
#define __EMPTY_3__ KC_TRNS, KC_TRNS, KC_TRNS
#define __EMPTY_6__ KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS

// BASE layer
// ==========

#define __BASE_L1__ OSL(VSCODE), KC_QUOTE, KC_COMMA, KC_DOT,  KC_P,   KC_Y
#define __BASE_L2__ OSL(SHELL_NAV), KC_A,     KC_O,     KC_E,    KC_U,   KC_I
#define __BASE_L3__ OSM(MOD_LSFT),KC_SEMICOLON, KC_Q,  KC_J,    KC_K,   KC_X

#define __BASE_R1__ KC_F,   KC_G,   KC_C,     KC_R,  KC_L,    KC_TAB
#define __BASE_R2__ KC_D,   KC_H,   KC_T,     KC_N,  KC_S,   LCTL(KC_BSPC)
#define __BASE_R3__ KC_B,   KC_M,   KC_W,     KC_V,  KC_Z,   OSM(MOD_RSFT)

#define __BASE_L_2THUMB__ MO(COMBINED),MO(KEYNAV)
#define __BASE_R_2THUMB__ KC_ENTER, KC_SPACE

// KEYNAV layer
// ============

#define __KEYNAV_L1__ KC_ESC, RCTL(KC_ENTER), RCTL(KC_K), RCTL(KC_Z), RCTL(KC_S), RCTL(KC_N)          
#define __KEYNAV_L2__ KC_TRNS, MO(KEYSEL), OBS_READMODE, RSFT(KC_TAB), KC_TAB, RCTL(KC_F)         
#define __KEYNAV_L3__ KC_TRNS, OBS_CMD, OBS_QUICKSW, OBS_CHECKBOX, RCTL(KC_B), KC_TRNS

#define __KEYNAV_R1__ KC_TRNS, KC_HOME, KC_UP, KC_END, KC_PGUP, KC_DELETE
#define __KEYNAV_R2__ LCTL(KC_LEFT), KC_LEFT, KC_DOWN, KC_RIGHT, LCTL(KC_RIGHT), KC_BSPC
#define __KEYNAV_R3__ KC_TRNS, RCTL(KC_C), RCTL(KC_X), RCTL(KC_V), KC_PGDN, RCTL(KC_DELETE)

// KEYSEL layer
// ============


#define __KEYSEL_L1__ __EMPTY_6__
#define __KEYSEL_L2__ __EMPTY_6__
#define __KEYSEL_L3__ __EMPTY_6__

#define __KEYSEL_R1__ KC_TRNS, RSFT(KC_HOME), RSFT(KC_UP), RSFT(KC_END), RSFT(KC_PGUP), KC_TRNS
#define __KEYSEL_R2__ RSFT(RCTL(KC_LEFT)), RSFT(KC_LEFT), RSFT(KC_DOWN), RSFT(KC_RIGHT), RSFT(RCTL(KC_RIGHT)), KC_TRNS
#define __KEYSEL_R3__ KC_TRNS, RCTL(KC_C), RCTL(KC_X), RCTL(KC_V), RSFT(KC_PGDN), KC_TRNS

// SHELL_NAV layer
// ===============

#define __SHELL_NAV_L1__ TO(BASE),KC_TRNS, SHELL_PGREP, SHELL_PLESS, SHELL_LESS, SH_EXIT
#define __SHELL_NAV_L2__ OSL(SHELL_SCREEN),KC_TRNS,SHELL_CDPRE,SHELL_LSLTR,SHELL_LS, SHELL_LSLA
#define __SHELL_NAV_L3__ KC_TRNS,SHELL_SCREEN_LIST, SHELL_SCREENRD, SHELL_SCREEN_NEW, SHELL_TAILF

#define __SHELL_NAV_R1__ SH_CLOSE, KC_HOME, KC_UP, KC_END, SH_CLEARSCR, SH_DEL_PATH
#define __SHELL_NAV_R2__ SH_WORD_LEFT, KC_LEFT, KC_DOWN, KC_RIGHT, SH_WORD_RIGHT, SH_DEL_WORD
#define __SHELL_NAV_R3__ KC_TRNS,   SH_DEL_TO_START, SH_RECALL, SH_SEARCH, SH_PASTE, SH_DEL_TO_END, SH_STOP

// SHELL_SCREEN layer
// ==================
#define __SHELL_SCREEN_L1__ TO(BASE),    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
#define __SHELL_SCREEN_L2__ TO(BASE), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, SCREEN_DETACH
#define __SHELL_SCREEN_L3__ KC_TRNS,   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS

#define __SHELL_SCREEN_R1__ KC_TRNS, SCREEN_7, SCREEN_8, SCREEN_9, SCREEN_RENAME, KC_TRNS
#define __SHELL_SCREEN_R2__ SCREEN_TAB_LEFT, SCREEN_4, SCREEN_5, SCREEN_6, SCREEN_TAB_RIGHT, SCREEN_COPY_MODE                              
#define __SHELL_SCREEN_R3__ KC_TRNS,         SCREEN_1, SCREEN_2, SCREEN_3, SCREEN_NUMBER, SCREEN_PASTE

// VSCODE layer
// ============

#define __VSCODE_L1__ TO(BASE), VS_GO_TO_TOP, VS_FIND_FILES, VS_CMT_BLOCK, VS_CMT_LINE, VS_RECENT
#define __VSCODE_L2__ KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, VS_SEL_BRACKET
#define __VSCODE_L3__ KC_TRNS, VS_GO_TO_BOTTOM, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS

#define __VSCODE_R1__ VS_COPYLINEDOWN, VS_REFERENCES, VS_DEFINITION, VS_IMPLEMENTATION, VS_LINE,   VS_BRACKET
#define __VSCODE_R2__ VS_CLOSETAB, VS_TABLEFT, VS_TABRIGHT, VS_SYMBOLEDITOR, VS_FILE,  VS_BACK
#define __VSCODE_R3__ VS_BM_CLEARALL,  VS_BM_PREV, VS_BM_NEXT,  VS_GROUP_1, VS_GROUP_2, VS_BM_TOGGLE

// COMBINED layer
// ==============

#define __COMBINED_L1__ KC_TILD,   KC_EXLM, KC_AT,   KC_HASH, KC_DLR, KC_PERC
#define __COMBINED_L2__ KC_GRAVE,  KC_LPRN, KC_RPRN, KC_LBRC, KC_RBRC, KC_UNDS
#define __COMBINED_L3__ KC_CIRC,  KC_COLN,  KC_DQUO,   KC_LCBR,   KC_RCBR,     KC_AMPR

#define __COMBINED_R1__ KC_PLUS,   KC_7,  KC_8,   KC_9,  KC_ASTR,  KC_PIPE
#define __COMBINED_R2__ KC_MINUS, KC_4,  KC_5,   KC_6,  KC_SLSH,  KC_BSLS                        
#define __COMBINED_R3__ KC_EQUAL,  KC_1,  KC_2,   KC_3,  KC_QUES,  KC_DOT