// GAME
// ============

#define __GAME_L0__  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
#define __GAME_L1__  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
#define __GAME_L2__  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
#define __GAME_L3__  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS

#define __GAME_R0__  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
#define __GAME_R1__  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
#define __GAME_R2__  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
#define __GAME_R3__  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS

#define __GAME_L_2THUMB__  KC_TRNS, KC_TRNS
#define __GAME_R_2THUMB__  KC_TRNS, KC_TRNS
#define __GAME_L_3THUMB__  KC_TRNS, KC_TRNS, KC_TRNS
#define __GAME_R_3THUMB__  KC_TRNS, KC_TRNS, KC_TRNS