#pragma once

// SYMBOLS
// ============

#define __SYMBOLS_L0__  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
#define __SYMBOLS_L1__  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
#define __SYMBOLS_L2__  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
#define __SYMBOLS_L3__  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS

#define __SYMBOLS_R0__  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
#define __SYMBOLS_R1__  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
#define __SYMBOLS_R2__  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
#define __SYMBOLS_R3__  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS

#define __SYMBOLS_L_2THUMB__  KC_TRNS, KC_TRNS
#define __SYMBOLS_R_2THUMB__  KC_TRNS, KC_TRNS
#define __SYMBOLS_L_3THUMB__  KC_TRNS, KC_TRNS, KC_TRNS
#define __SYMBOLS_R_3THUMB__  KC_TRNS, KC_TRNS, KC_TRNS